name: Deploy iOS to TestFlight

on:
  push:
    branches:
      - main # O la rama que prefieras para desplegar

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set to XCode 16.x.y
        uses: maxim-lobanov/setup-xcode@v1
        with:
           xcode-version: '16.2.0'

      - name: Decode and install certificates
        env:
          DEVELOPER_CERTIFICATE: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          DEVELOPER_CERTIFICATE_PASSWORD: ${{ secrets.P12_PASSWORD }}
          PROVISIONING_PROFILE: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        run: |
          echo "$DEVELOPER_CERTIFICATE" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$DEVELOPER_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          echo "$PROVISIONING_PROFILE" | base64 --decode > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mv profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build .ipa file
        run: |
          xcodebuild -workspace SMOC.xcworkspace \
            -scheme SMOC \
            -configuration Release \
            -archivePath build/SMOC.xcarchive \
            archive

          xcodebuild -exportArchive \
            -archivePath build/SMOC.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/

      - name: Upload to TestFlight
        env:
          APPSTORE_EMAIL: ${{ secrets.APPSTORE_EMAIL }}
          APPSTORE_PASSWORD: ${{ secrets.APPSTORE_PASSWORD }}
          APPSTORE_TEAM_ID: ${{ secrets.APPSTORE_TEAM_ID }}
        if: false
        run: |
          xcrun altool --upload-app -f build/SMOC.ipa -t ios \
            --apiKey "$APPSTORE_EMAIL" \
            --apiIssuer "$APPSTORE_TEAM_ID"
