name: manual-workflow

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
