name: manual-workflow

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: 'Tu nombre'
        required: true
        default: 'Mundo'

jobs:
  saludo:
    runs-on: macos-latest
    steps:
      - name: Mostrar saludo
        run: echo "Hola, ${{ github.event.inputs.nombre }}!"
