name: sample-workflow

on:
  #push:
  #  branches:  [main, develop]
  workflow_dispatch:

jobs:
  sample-job:
    runs-on: macos-latest

    steps:
      - name: Say something
        run: echo 'Hello World'