name: testflight-debug

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup Keychain
        if: always()
        run: security delete-keychain build.keychain
